CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64),
	`name` text,
	`email` varchar(320),
	`passwordHash` varchar(255),
	`company` varchar(255),
	`phone` varchar(64),
	`loginMethod` varchar(64) DEFAULT 'email',
	`role` enum('user','admin','superadmin') NOT NULL DEFAULT 'user',
	`status` enum('active','pending','suspended') NOT NULL DEFAULT 'pending',
	`emailVerified` boolean NOT NULL DEFAULT false,
	`emailVerifyToken` varchar(128),
	`emailVerifyExpiry` timestamp,
	`resetToken` varchar(128),
	`resetTokenExpiry` timestamp,
	`lastLoginAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`)
);
