import { Link } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Users, TrendingUp, Wallet, Shield, Globe, Zap, ChevronRight,
  CheckCircle2, Star, Award, BarChart3, RefreshCw, ArrowRight,
  DollarSign, Percent, Clock, Building2, Code2, Brain, Server,
  HelpCircle, ChevronDown,
} from "lucide-react";
import { useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const COMMISSION_TABLE = [
  { category: "Blockchain Infrastructure", icon: Server, rate: "12%", recurrence: "Monthly", min: "€ 5.000", note: "" },
  { category: "Smart Contract Development", icon: Code2, rate: "10%", recurrence: "One-time", min: "€ 3.000", note: "" },
  { category: "AI & Machine Learning", icon: Brain, rate: "15%", recurrence: "Monthly", min: "€ 8.000", note: "" },
  { category: "Web3 Platform", icon: Globe, rate: "10%", recurrence: "Monthly", min: "€ 4.000", note: "" },
  { category: "Enterprise Consulting", icon: Building2, rate: "8%", recurrence: "One-time", min: "€ 10.000", note: "" },
  { category: "DYN Token Services", icon: Zap, rate: "5%", recurrence: "One-time", min: "€ 1.000", note: "In DYN" },
];

const BENEFITS = [
  { icon: TrendingUp, titleIt: "Commissioni fino al 15%", titleEn: "Commissions up to 15%", descIt: "Percentuali competitive su tutti i servizi Dyneros, con bonus per volumi elevati.", descEn: "Competitive rates on all Dyneros services, with bonuses for high volumes." },
  { icon: RefreshCw, titleIt: "Ricorrenti mensili", titleEn: "Monthly recurring", descIt: "Guadagna ogni mese finché il cliente rimane attivo. Nessun limite di tempo.", descEn: "Earn every month as long as the client stays active. No time limit." },
  { icon: Clock, titleIt: "Finestra 90 giorni", titleEn: "90-day window", descIt: "Ogni lead è attribuito per 90 giorni. Hai tempo per chiudere la trattativa.", descEn: "Every lead is attributed for 90 days. You have time to close the deal." },
  { icon: Wallet, titleIt: "Pagamenti flessibili", titleEn: "Flexible payments", descIt: "Bonifico bancario, PayPal, USDT, USDC, BTC, ETH o token DYN nativi.", descEn: "Bank transfer, PayPal, USDT, USDC, BTC, ETH or native DYN tokens." },
  { icon: BarChart3, titleIt: "Dashboard in tempo reale", titleEn: "Real-time dashboard", descIt: "Monitora click, lead, conversioni e pagamenti dal tuo pannello personale.", descEn: "Monitor clicks, leads, conversions and payments from your personal panel." },
  { icon: Shield, titleIt: "Contratto trasparente", titleEn: "Transparent contract", descIt: "Accordo digitale firmato, storico completo e rendicontazione chiara.", descEn: "Signed digital agreement, complete history and clear reporting." },
];

const FAQS = [
  {
    qIt: "Chi può diventare affiliato Dyneros?",
    qEn: "Who can become a Dyneros affiliate?",
    aIt: "Chiunque: consulenti IT, agenzie digitali, sviluppatori blockchain, professionisti finanziari, influencer tech. Non è richiesta esperienza tecnica specifica.",
    aEn: "Anyone: IT consultants, digital agencies, blockchain developers, financial professionals, tech influencers. No specific technical experience required.",
  },
  {
    qIt: "Quanto tempo ci vuole per l'approvazione?",
    qEn: "How long does approval take?",
    aIt: "Generalmente 24-48 ore lavorative. Riceverai una email di conferma con il tuo codice referral e l'accesso al pannello.",
    aEn: "Generally 24-48 business hours. You will receive a confirmation email with your referral code and access to the panel.",
  },
  {
    qIt: "Quando vengono pagate le commissioni?",
    qEn: "When are commissions paid?",
    aIt: "Le commissioni vengono liquidate entro il 15 del mese successivo alla conferma del contratto cliente. Soglia minima: €50.",
    aEn: "Commissions are settled by the 15th of the month following client contract confirmation. Minimum threshold: €50.",
  },
  {
    qIt: "Cos'è il programma Sub-Affiliato?",
    qEn: "What is the Sub-Affiliate program?",
    aIt: "Puoi reclutare altri affiliati sotto di te. Per ogni conversione generata dai tuoi sub-affiliati, ricevi il 50% della loro commissione come override.",
    aEn: "You can recruit other affiliates under you. For each conversion generated by your sub-affiliates, you receive 50% of their commission as an override.",
  },
  {
    qIt: "Come funziona il tracking dei referral?",
    qEn: "How does referral tracking work?",
    aIt: "Il tuo codice univoco viene tracciato via cookie per 90 giorni. Ogni lead che arriva dal tuo link è attribuito a te per l'intera finestra di attribuzione.",
    aEn: "Your unique code is tracked via cookie for 90 days. Every lead that comes from your link is attributed to you for the entire attribution window.",
  },
  {
    qIt: "Posso promuovere Dyneros sui social media?",
    qEn: "Can I promote Dyneros on social media?",
    aIt: "Sì, puoi usare tutti i canali digitali: social, blog, newsletter, podcast, eventi. Ti forniamo materiali di marketing su richiesta.",
    aEn: "Yes, you can use all digital channels: social, blog, newsletter, podcast, events. We provide marketing materials on request.",
  },
];

export default function Affiliazione() {
  const { language, t } = useLanguage();
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const isIT = language === "it";

  return (
    <div className="min-h-screen bg-[#0a0e1a] text-white">
      <Navbar />

      <section className="relative pt-32 pb-20 px-4 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#0a0e1a] via-[#0d1530] to-[#0a0e1a]" />
        <div className="absolute top-20 left-1/4 w-96 h-96 bg-[#00d4ff]/5 rounded-full blur-3xl" />
        <div className="absolute bottom-0 right-1/4 w-80 h-80 bg-[#7c3aed]/5 rounded-full blur-3xl" />
        <div className="relative max-w-5xl mx-auto text-center">
          <Badge className="mb-6 bg-[#00d4ff]/10 text-[#00d4ff] border border-[#00d4ff]/20 px-4 py-1.5 text-sm">
            {isIT ? "Programma Affiliazione 2024" : "Affiliate Program 2024"}
          </Badge>
          <h1 className="text-5xl md:text-7xl font-bold mb-6 leading-tight">
            {isIT ? "Guadagna con" : "Earn with"}{" "}
            <span className="bg-gradient-to-r from-[#00d4ff] to-[#7c3aed] bg-clip-text text-transparent">
              Dyneros
            </span>
          </h1>
          <p className="text-xl text-gray-400 mb-10 max-w-3xl mx-auto leading-relaxed">
            {isIT
              ? "Porta clienti a Dyneros e guadagna commissioni ricorrenti fino al 15% su ogni contratto. Finestra di attribuzione 90 giorni, pagamenti flessibili in fiat o crypto."
              : "Bring clients to Dyneros and earn recurring commissions up to 15% on every contract. 90-day attribution window, flexible payments in fiat or crypto."}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/affiliazione/candidatura">
              <Button size="lg" className="bg-gradient-to-r from-[#00d4ff] to-[#7c3aed] hover:opacity-90 text-white px-8 py-4 text-lg font-semibold">
                {isIT ? "Diventa Affiliato" : "Become an Affiliate"}
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
            <Link href="/affiliazione/sub-affiliato">
              <Button size="lg" variant="outline" className="border-[#00d4ff]/30 text-[#00d4ff] hover:bg-[#00d4ff]/10 px-8 py-4 text-lg">
                {isIT ? "Diventa Sub-Affiliato" : "Become Sub-Affiliate"}
              </Button>
            </Link>
          </div>
          <div className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-6">
            {[
              { value: "15%", label: isIT ? "Commissione max" : "Max commission" },
              { value: "90gg", label: isIT ? "Finestra attribuzione" : "Attribution window" },
              { value: "24h", label: isIT ? "Approvazione" : "Approval" },
              { value: "7+", label: isIT ? "Metodi pagamento" : "Payment methods" },
            ].map((stat) => (
              <div key={stat.value} className="bg-white/5 rounded-xl p-4 border border-white/10">
                <div className="text-3xl font-bold text-[#00d4ff] mb-1">{stat.value}</div>
                <div className="text-sm text-gray-400">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-4 bg-[#0d1530]/50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              {isIT ? "Come funziona" : "How it works"}
            </h2>
            <p className="text-gray-400 text-lg">
              {isIT ? "Tre passi per iniziare a guadagnare" : "Three steps to start earning"}
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { step: "01", icon: Users, titleIt: "Candidati", titleEn: "Apply", descIt: "Compila il form di candidatura. Approvazione in 24-48 ore.", descEn: "Fill in the application form. Approval in 24-48 hours." },
              { step: "02", icon: Globe, titleIt: "Condividi", titleEn: "Share", descIt: "Ricevi il tuo codice univoco e il link referral personalizzato.", descEn: "Get your unique code and personalized referral link." },
              { step: "03", icon: DollarSign, titleIt: "Guadagna", titleEn: "Earn", descIt: "Ogni conversione genera commissioni automaticamente nel tuo pannello.", descEn: "Every conversion automatically generates commissions in your panel." },
            ].map((item) => (
              <div key={item.step} className="relative">
                <div className="bg-[#0a0e1a] border border-white/10 rounded-2xl p-8 h-full">
                  <div className="text-6xl font-black text-white/5 mb-4">{item.step}</div>
                  <item.icon className="w-10 h-10 text-[#00d4ff] mb-4" />
                  <h3 className="text-xl font-bold mb-3">{isIT ? item.titleIt : item.titleEn}</h3>
                  <p className="text-gray-400">{isIT ? item.descIt : item.descEn}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              {isIT ? "Commissioni per categoria" : "Commissions by category"}
            </h2>
            <p className="text-gray-400 text-lg">
              {isIT ? "Tariffe competitive su tutti i servizi Dyneros" : "Competitive rates on all Dyneros services"}
            </p>
          </div>
          <div className="overflow-x-auto rounded-2xl border border-white/10">
            <table className="w-full">
              <thead>
                <tr className="bg-white/5 border-b border-white/10">
                  <th className="text-left px-6 py-4 text-gray-400 font-medium">{isIT ? "Categoria" : "Category"}</th>
                  <th className="text-center px-6 py-4 text-gray-400 font-medium">{isIT ? "Commissione" : "Commission"}</th>
                  <th className="text-center px-6 py-4 text-gray-400 font-medium">{isIT ? "Ricorrenza" : "Recurrence"}</th>
                  <th className="text-center px-6 py-4 text-gray-400 font-medium">{isIT ? "Contratto min." : "Min. contract"}</th>
                  <th className="text-center px-6 py-4 text-gray-400 font-medium">Note</th>
                </tr>
              </thead>
              <tbody>
                {COMMISSION_TABLE.map((row, i) => (
                  <tr key={i} className="border-b border-white/5 hover:bg-white/3 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <row.icon className="w-5 h-5 text-[#00d4ff]" />
                        <span className="font-medium">{row.category}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <span className="text-[#00d4ff] font-bold text-lg">{row.rate}</span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <Badge className={row.recurrence === "Monthly" ? "bg-green-500/10 text-green-400 border-green-500/20" : "bg-blue-500/10 text-blue-400 border-blue-500/20"}>
                        {row.recurrence}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 text-center text-gray-300">{row.min}</td>
                    <td className="px-6 py-4 text-center text-gray-500 text-sm">{row.note || "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="text-center text-gray-500 text-sm mt-4">
            {isIT ? "* Le commissioni ricorrenti si applicano per tutta la durata del contratto cliente." : "* Recurring commissions apply for the entire duration of the client contract."}
          </p>
        </div>
      </section>

      <section className="py-20 px-4 bg-[#0d1530]/50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              {isIT ? "Vantaggi del programma" : "Program benefits"}
            </h2>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {BENEFITS.map((b, i) => (
              <Card key={i} className="bg-[#0a0e1a] border-white/10 hover:border-[#00d4ff]/30 transition-colors">
                <CardContent className="p-6">
                  <b.icon className="w-8 h-8 text-[#00d4ff] mb-4" />
                  <h3 className="font-bold text-lg mb-2">{isIT ? b.titleIt : b.titleEn}</h3>
                  <p className="text-gray-400 text-sm leading-relaxed">{isIT ? b.descIt : b.descEn}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              {isIT ? "Programma Sub-Affiliato" : "Sub-Affiliate Program"}
            </h2>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto">
              {isIT
                ? "Sei già affiliato? Recluta altri affiliati sotto di te e guadagna il 50% delle loro commissioni come override."
                : "Already an affiliate? Recruit other affiliates under you and earn 50% of their commissions as an override."}
            </p>
          </div>
          <div className="bg-gradient-to-r from-[#00d4ff]/5 to-[#7c3aed]/5 border border-[#00d4ff]/20 rounded-2xl p-8">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <div className="flex items-center gap-3 mb-4">
                  <Award className="w-8 h-8 text-[#7c3aed]" />
                  <h3 className="text-xl font-bold">{isIT ? "Override del 50%" : "50% Override"}</h3>
                </div>
                <ul className="space-y-3">
                  {(isIT ? [
                    "Recluta affiliati con il tuo codice referral",
                    "Ogni loro conversione ti genera un override del 50%",
                    "Nessun limite al numero di sub-affiliati",
                    "Tracking separato nel tuo pannello",
                  ] : [
                    "Recruit affiliates with your referral code",
                    "Each of their conversions generates a 50% override for you",
                    "No limit on the number of sub-affiliates",
                    "Separate tracking in your panel",
                  ]).map((item, i) => (
                    <li key={i} className="flex items-center gap-2 text-gray-300">
                      <CheckCircle2 className="w-4 h-4 text-[#00d4ff] flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="bg-[#0a0e1a] rounded-xl p-6 border border-white/10">
                <div className="text-center mb-4">
                  <div className="text-sm text-gray-400 mb-1">{isIT ? "Esempio di guadagno" : "Earnings example"}</div>
                  <div className="text-3xl font-bold text-[#00d4ff]">€ 1.800 / {isIT ? "mese" : "month"}</div>
                </div>
                <div className="space-y-2 text-sm">
                  <div className="flex justify-between text-gray-400">
                    <span>{isIT ? "3 clienti AI (€ 10k/mese)" : "3 AI clients (€ 10k/month)"}</span>
                    <span className="text-green-400">+€ 1.350</span>
                  </div>
                  <div className="flex justify-between text-gray-400">
                    <span>{isIT ? "Override 5 sub-affiliati" : "Override 5 sub-affiliates"}</span>
                    <span className="text-[#7c3aed]">+€ 450</span>
                  </div>
                  <div className="border-t border-white/10 pt-2 flex justify-between font-bold">
                    <span>Totale</span>
                    <span className="text-[#00d4ff]">€ 1.800</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-20 px-4 bg-[#0d1530]/50">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">FAQ</h2>
          </div>
          <div className="space-y-3">
            {FAQS.map((faq, i) => (
              <div key={i} className="bg-[#0a0e1a] border border-white/10 rounded-xl overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-white/5 transition-colors"
                >
                  <span className="font-medium">{isIT ? faq.qIt : faq.qEn}</span>
                  <ChevronDown className={`w-5 h-5 text-gray-400 transition-transform ${openFaq === i ? "rotate-180" : ""}`} />
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-4 text-gray-400 leading-relaxed border-t border-white/5 pt-4">
                    {isIT ? faq.aIt : faq.aEn}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            {isIT ? "Pronto a iniziare?" : "Ready to start?"}
          </h2>
          <p className="text-gray-400 text-lg mb-8">
            {isIT
              ? "Unisciti alla rete di affiliati Dyneros e inizia a guadagnare commissioni ricorrenti."
              : "Join the Dyneros affiliate network and start earning recurring commissions."}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/affiliazione/candidatura">
              <Button size="lg" className="bg-gradient-to-r from-[#00d4ff] to-[#7c3aed] hover:opacity-90 text-white px-8 py-4 text-lg font-semibold">
                {isIT ? "Candidati come Affiliato" : "Apply as Affiliate"}
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
            <Link href="/affiliazione/sub-affiliato">
              <Button size="lg" variant="outline" className="border-white/20 text-white hover:bg-white/10 px-8 py-4 text-lg">
                {isIT ? "Candidati come Sub-Affiliato" : "Apply as Sub-Affiliate"}
              </Button>
            </Link>
          </div>
          <p className="text-gray-500 text-sm mt-6">
            {isIT
              ? "Hai già un codice affiliato? "
              : "Already have an affiliate code? "}
            <Link href="/dashboard/affiliato" className="text-[#00d4ff] hover:underline">
              {isIT ? "Accedi al tuo pannello" : "Access your panel"}
            </Link>
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
