import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "it" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  it: {
    "nav.home": "Home",
    "nav.chain": "Dyneros Chain",
    "nav.platform": "Piattaforma",
    "nav.solutions": "Soluzioni",
    "nav.developers": "Sviluppatori",
    "nav.company": "Azienda",
    "nav.login": "Accedi",
    "nav.register": "Inizia Ora",
    "nav.dashboard": "Dashboard",
    "nav.logout": "Esci",
    "dash.overview": "Panoramica",
    "dash.projects": "Progetti",
    "dash.tickets": "Ticket",
    "dash.documents": "Documenti",
    "dash.contracts": "Contratti",
    "dash.invoices": "Fatture",
    "dash.blockchain": "Blockchain Console",
    "dash.wallet": "Wallet & Asset",
    "dash.smartcontracts": "Smart Contracts",
    "dash.domains": "Domini & Deploy",
    "dash.ai": "AI & Automazioni",
    "dash.team": "Team & Referenti",
    "dash.notifications": "Notifiche",
    "dash.settings": "Impostazioni",
    "dash.security": "Sicurezza",
    "dash.apikeys": "Chiavi API",
    "dash.knowledge": "Knowledge Base",
    "dash.email": "Email & Notifiche",
    "status.active": "Attivo",
    "status.inactive": "Inattivo",
    "status.pending": "In Attesa",
    "status.completed": "Completato",
    "status.in_progress": "In Corso",
    "status.on_hold": "In Pausa",
    "status.planning": "Pianificazione",
    "status.open": "Aperto",
    "status.resolved": "Risolto",
    "status.closed": "Chiuso",
    "status.paid": "Pagata",
    "status.unpaid": "Non Pagata",
    "status.overdue": "Scaduta",
    "status.draft": "Bozza",
    "status.signed": "Firmato",
    "status.expired": "Scaduto",
    "priority.low": "Bassa",
    "priority.medium": "Media",
    "priority.high": "Alta",
    "priority.critical": "Critica",
    "action.search": "Cerca...",
    "action.filter": "Filtra",
    "action.create": "Crea Nuovo",
    "action.save": "Salva",
    "action.cancel": "Annulla",
    "action.delete": "Elimina",
    "action.edit": "Modifica",
    "action.view": "Visualizza",
    "action.download": "Scarica",
    "action.copy": "Copia",
    "action.copied": "Copiato!",
    "action.markread": "Segna come letto",
    "action.markallread": "Segna tutti come letti",
    "action.generate": "Genera",
    "action.revoke": "Revoca",
    "action.send": "Invia",
    "action.test": "Test",
    "label.name": "Nome",
    "label.email": "Email",
    "label.company": "Azienda",
    "label.status": "Stato",
    "label.priority": "Priorità",
    "label.date": "Data",
    "label.amount": "Importo",
    "label.type": "Tipo",
    "label.description": "Descrizione",
    "label.address": "Indirizzo",
    "label.network": "Rete",
    "label.balance": "Saldo",
    "label.verified": "Verificato",
    "label.all": "Tutti",
    "label.loading": "Caricamento...",
    "label.nodata": "Nessun dato disponibile",
    "label.total": "Totale",
    "label.sla": "SLA",
    "label.progress": "Progresso",
    "label.eta": "Data Prevista",
    "label.created": "Creato",
    "label.updated": "Aggiornato",
    "label.expires": "Scade",
    "label.role": "Ruolo",
    "label.permissions": "Permessi",
    "label.lastused": "Ultimo Utilizzo",
    "label.session": "Sessione",
    "label.ip": "Indirizzo IP",
    "label.device": "Dispositivo",
    "label.language": "Lingua",
    "label.theme": "Tema",
    "label.dark": "Scuro",
    "label.light": "Chiaro",
    "label.italian": "Italiano",
    "label.english": "English",
    "msg.success": "Operazione completata con successo",
    "msg.error": "Si è verificato un errore",
    "msg.saved": "Salvato con successo",
    "msg.deleted": "Eliminato con successo",
    "msg.sent": "Inviato con successo",
    "msg.generated": "Generato con successo",
    "msg.revoked": "Revocato con successo",
    "msg.comingsoon": "Funzionalità in arrivo",
  },
  en: {
    "nav.home": "Home",
    "nav.chain": "Dyneros Chain",
    "nav.platform": "Platform",
    "nav.solutions": "Solutions",
    "nav.developers": "Developers",
    "nav.company": "Company",
    "nav.login": "Login",
    "nav.register": "Get Started",
    "nav.dashboard": "Dashboard",
    "nav.logout": "Logout",
    "dash.overview": "Overview",
    "dash.projects": "Projects",
    "dash.tickets": "Tickets",
    "dash.documents": "Documents",
    "dash.contracts": "Contracts",
    "dash.invoices": "Invoices",
    "dash.blockchain": "Blockchain Console",
    "dash.wallet": "Wallet & Assets",
    "dash.smartcontracts": "Smart Contracts",
    "dash.domains": "Domains & Deploy",
    "dash.ai": "AI & Automations",
    "dash.team": "Team & Contacts",
    "dash.notifications": "Notifications",
    "dash.settings": "Settings",
    "dash.security": "Security",
    "dash.apikeys": "API Keys",
    "dash.knowledge": "Knowledge Base",
    "dash.email": "Email & Notifications",
    "status.active": "Active",
    "status.inactive": "Inactive",
    "status.pending": "Pending",
    "status.completed": "Completed",
    "status.in_progress": "In Progress",
    "status.on_hold": "On Hold",
    "status.planning": "Planning",
    "status.open": "Open",
    "status.resolved": "Resolved",
    "status.closed": "Closed",
    "status.paid": "Paid",
    "status.unpaid": "Unpaid",
    "status.overdue": "Overdue",
    "status.draft": "Draft",
    "status.signed": "Signed",
    "status.expired": "Expired",
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.critical": "Critical",
    "action.search": "Search...",
    "action.filter": "Filter",
    "action.create": "Create New",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.view": "View",
    "action.download": "Download",
    "action.copy": "Copy",
    "action.copied": "Copied!",
    "action.markread": "Mark as read",
    "action.markallread": "Mark all as read",
    "action.generate": "Generate",
    "action.revoke": "Revoke",
    "action.send": "Send",
    "action.test": "Test",
    "label.name": "Name",
    "label.email": "Email",
    "label.company": "Company",
    "label.status": "Status",
    "label.priority": "Priority",
    "label.date": "Date",
    "label.amount": "Amount",
    "label.type": "Type",
    "label.description": "Description",
    "label.address": "Address",
    "label.network": "Network",
    "label.balance": "Balance",
    "label.verified": "Verified",
    "label.all": "All",
    "label.loading": "Loading...",
    "label.nodata": "No data available",
    "label.total": "Total",
    "label.sla": "SLA",
    "label.progress": "Progress",
    "label.eta": "ETA",
    "label.created": "Created",
    "label.updated": "Updated",
    "label.expires": "Expires",
    "label.role": "Role",
    "label.permissions": "Permissions",
    "label.lastused": "Last Used",
    "label.session": "Session",
    "label.ip": "IP Address",
    "label.device": "Device",
    "label.language": "Language",
    "label.theme": "Theme",
    "label.dark": "Dark",
    "label.light": "Light",
    "label.italian": "Italiano",
    "label.english": "English",
    "msg.success": "Operation completed successfully",
    "msg.error": "An error occurred",
    "msg.saved": "Saved successfully",
    "msg.deleted": "Deleted successfully",
    "msg.sent": "Sent successfully",
    "msg.generated": "Generated successfully",
    "msg.revoked": "Revoked successfully",
    "msg.comingsoon": "Feature coming soon",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "it",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("dyneros_lang");
    return (stored === "en" || stored === "it") ? stored : "it";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("dyneros_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations["it"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
