import React, { createContext, useContext, useState } from "react";

export type Language = "it" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  it: {
    // NAV
    "nav.chain": "Dyneros Chain",
    "nav.platform": "Piattaforma",
    "nav.solutions": "Soluzioni",
    "nav.developers": "Sviluppatori",
    "nav.pricing": "Prezzi",
    "nav.company": "Azienda",
    "nav.login": "Accedi",
    "nav.register": "Inizia Ora",
    "nav.dashboard": "Dashboard",
    "nav.logout": "Esci",
    // HERO
    "hero.badge": "Dyneros Chain — Attiva su Mainnet",
    "hero.headline1": "Infrastruttura Digitale",
    "hero.headline2": "per la Prossima Generazione",
    "hero.headline3": "di Imprese",
    "hero.sub": "Dyneros costruisce sistemi scalabili e sicuri per le imprese moderne — on-chain e oltre.",
    "hero.cta.start": "Inizia Ora",
    "hero.cta.explore": "Esplora Dyneros Chain",
    "hero.stat1.label": "Uptime di Rete",
    "hero.stat2.label": "Transazioni Elaborate",
    "hero.stat3.label": "Clienti Enterprise",
    // TRUST BAR
    "trust.p1.label": "Infrastruttura enterprise-ready",
    "trust.p1.desc": "Progettata per conformità, controllo e prevedibilità su larga scala.",
    "trust.p2.label": "Rete di sviluppo globale",
    "trust.p2.desc": "15 ingegneri core e 100+ collaboratori in ogni fuso orario.",
    "trust.p3.label": "Scalabile fin dal primo giorno",
    "trust.p3.desc": "Architettura che cresce con la tua azienda — senza re-platforming.",
    // CHAIN SECTION
    "chain.badge": "Dyneros Chain",
    "chain.headline": "La Blockchain Costruita per le Imprese",
    "chain.sub": "Un layer blockchain dedicato e ad alte prestazioni per le aziende che necessitano di controllo, prevedibilità e conformità — senza il rumore delle reti pubbliche.",
    "chain.vs.public.title": "Blockchain pubbliche",
    "chain.vs.public.desc": "Costi imprevedibili, dati pubblici, nessun controllo sull'infrastruttura.",
    "chain.vs.dyneros.title": "Dyneros Chain",
    "chain.vs.dyneros.desc": "Costi fissi, dati privati, piena proprietà del tuo ambiente blockchain.",
    "chain.feat1.title": "Alta Disponibilità",
    "chain.feat1.desc": "99.9% uptime garantito con ridondanza multi-nodo e failover automatico.",
    "chain.feat2.title": "EVM Compatibile",
    "chain.feat2.desc": "Distribuisci i tuoi smart contract Solidity esistenti senza modifiche.",
    "chain.feat3.title": "Conformità Integrata",
    "chain.feat3.desc": "Strumenti di audit e controllo degli accessi progettati per ambienti regolamentati.",
    "chain.feat4.title": "Costi Prevedibili",
    "chain.feat4.desc": "Tariffazione fissa per transazione — nessuna sorpresa da fee di gas variabili.",
    "chain.feat5.title": "Dati Privati",
    "chain.feat5.desc": "La tua chain, i tuoi dati. Nessuna esposizione pubblica per impostazione predefinita.",
    "chain.feat6.title": "Supporto Enterprise",
    "chain.feat6.desc": "SLA dedicato, account manager e supporto tecnico diretto 24/7.",
    "chain.network.title": "Accesso alla Rete",
    "chain.network.sub": "Connettiti direttamente all'infrastruttura Dyneros Chain.",
    "chain.quote": "Non una criptovaluta. Un'infrastruttura.",
    "chain.explorer": "Apri Explorer",
    "chain.wallet": "Accedi al Wallet",
    // PLATFORM SECTION
    "platform.badge": "Piattaforma",
    "platform.headline": "L'Esperienza Completa della Piattaforma",
    "platform.sub": "Tutti gli strumenti di cui il tuo team ha bisogno per operare, monitorare e gestire la tua infrastruttura blockchain.",
    "platform.explorer.title": "Explorer — explorer.dyneros.com",
    "platform.explorer.label": "Explorer",
    "platform.explorer.desc": "Visibilità completa su transazioni e blocchi della Dyneros Chain.",
    "platform.wallet.title": "Wallet — wallet.dyneros.com",
    "platform.wallet.label": "Wallet",
    "platform.wallet.desc": "Gestione sicura degli asset e degli account per utenti enterprise.",
    "platform.dashboard.title": "Dashboard di Rete",
    "platform.dashboard.label": "Dashboard",
    "platform.dashboard.desc": "Panoramica in tempo reale della chain con metriche di performance e indicatori di salute.",
    "platform.search": "Cerca transazioni, blocchi, indirizzi...",
    "platform.balance": "Saldo Totale",
    "platform.send": "Invia",
    "platform.receive": "Ricevi",
    "platform.history": "Cronologia",
    "platform.confirmed": "Confermata",
    "platform.block": "Blocco",
    "platform.validators": "Validatori",
    "platform.blocks": "Blocchi",
    // SOLUTIONS SECTION
    "solutions.badge": "Soluzioni",
    "solutions.headline": "Costruito per il Tuo Settore",
    "solutions.sub": "Problemi reali. Soluzioni concrete. Risultati misurabili.",
    "solutions.problem": "Problema",
    "solutions.solution": "Soluzione",
    "solutions.outcome": "Risultato",
    "solutions.ind1.name": "Manifattura",
    "solutions.ind1.problem": "Lacune nella tracciabilità lungo le supply chain creano dispute e fallimenti di conformità.",
    "solutions.ind1.solution": "Supply chain on-chain con registrazioni immutabili in ogni fase produttiva.",
    "solutions.ind1.outcome": "Audit trail completo, zero dispute, conformità normativa by default.",
    "solutions.ind2.name": "Logistica",
    "solutions.ind2.problem": "Frodi documentali e certificazioni manuali rallentano le operazioni transfrontaliere.",
    "solutions.ind2.solution": "Certificazione digitale con verifica crittografica di ogni spedizione.",
    "solutions.ind2.outcome": "Registrazioni di spedizione immutabili, sdoganamento più rapido, eliminazione delle frodi.",
    "solutions.ind3.name": "Finanza",
    "solutions.ind3.problem": "Cicli di regolamento lenti e alti costi di transazione erodono i margini.",
    "solutions.ind3.solution": "Canali di pagamento interni costruiti su Dyneros Chain per regolamento istantaneo.",
    "solutions.ind3.outcome": "Trasferimenti istantanei e a basso costo con piena auditabilità e conformità.",
    "solutions.ind4.name": "Retail",
    "solutions.ind4.problem": "I programmi fedeltà frammentati non riescono a fidelizzare i clienti né a generare dati.",
    "solutions.ind4.solution": "Infrastruttura fedeltà tokenizzata — programmabile, portabile, interoperabile.",
    "solutions.ind4.outcome": "Premi unificati, maggiore fidelizzazione e customer intelligence azionabile.",
    "solutions.ind5.name": "Gaming",
    "solutions.ind5.problem": "Le economie di gioco vengono sfruttate, minando la fiducia dei giocatori e la monetizzazione.",
    "solutions.ind5.solution": "Economia di asset digitali verificabile con proprietà e provenienza on-chain.",
    "solutions.ind5.outcome": "Proprietà verificabile, valore reale degli asset, economia di gioco sostenibile.",
    "solutions.ind6.name": "Startup",
    "solutions.ind6.problem": "I costi e la complessità dell'infrastruttura rallentano i cicli di sviluppo del prodotto.",
    "solutions.ind6.solution": "Fondamenta blockchain scalabili con infrastruttura gestita fin dal primo giorno.",
    "solutions.ind6.outcome": "Lancia più velocemente, scala a costi inferiori, concentrati sul prodotto non sull'infrastruttura.",
    // SERVICES SECTION
    "services.badge": "Servizi",
    "services.headline": "Cosa Costruiamo",
    "services.sub": "Dal software personalizzato all'infrastruttura blockchain enterprise — costruiamo sistemi che funzionano su scala, fin dal primo giorno.",
    "services.cta": "Parlaci",
    "services.s1.title": "Sviluppo Software",
    "services.s1.desc": "Software di livello produzione progettato per affidabilità, performance e manutenibilità a lungo termine.",
    "services.s2.title": "Piattaforme Web",
    "services.s2.desc": "Applicazioni web scalabili costruite per traffico enterprise, flussi di lavoro complessi e un'esperienza utente fluida.",
    "services.s3.title": "Soluzioni Blockchain",
    "services.s3.desc": "Integrazione blockchain end-to-end — dall'architettura al deployment su Dyneros Chain o reti personalizzate.",
    "services.s4.title": "Sistemi Personalizzati",
    "services.s4.desc": "Infrastruttura e strumenti su misura progettati attorno ai tuoi requisiti operativi, non il contrario.",
    // DEVELOPERS SECTION
    "dev.badge": "Per i Costruttori",
    "dev.headline": "Costruisci su Dyneros",
    "dev.sub": "Accedi all'infrastruttura Dyneros Chain attraverso interfacce pulite e ben documentate. Nessuna complessità interna esposta — solo gli strumenti di cui hai bisogno per costruire.",
    "dev.cta": "Inizia a Costruire",
    "dev.ap1.title": "Accesso alla Rete",
    "dev.ap1.desc": "Connetti le tue applicazioni direttamente alla mainnet Dyneros Chain o a un'istanza privata dedicata.",
    "dev.ap2.title": "Deploy di Smart Contract",
    "dev.ap2.desc": "Distribuisci e gestisci smart contract su Dyneros Chain usando gli strumenti di sviluppo che già conosci.",
    "dev.ap3.title": "Integrazione API",
    "dev.ap3.desc": "API RESTful e GraphQL per leggere lo stato della chain, inviare transazioni e monitorare gli eventi.",
    "dev.deployed": "Deployato a:",
    // CASE STUDIES
    "cases.badge": "Prove",
    "cases.headline": "Risultati che Parlano",
    "cases.sub": "Deployment reali. Impatto misurabile. Nessun marketing vuoto.",
    "cases.c1.metric": "Riduzione dei costi operativi",
    "cases.c1.industry": "Logistica",
    "cases.c1.desc": "Un operatore logistico globale ha migrato la certificazione documentale su Dyneros Chain, eliminando i flussi di verifica manuale e le dispute transfrontaliere.",
    "cases.c1.tag1": "Gestione Documenti",
    "cases.c1.tag2": "Supply Chain",
    "cases.c2.metric": "Transazioni di asset digitali nel Q1",
    "cases.c2.industry": "Gaming",
    "cases.c2.desc": "Una grande piattaforma gaming ha distribuito un'economia di asset digitali su Dyneros Chain, abilitando la proprietà verificabile e il trading a valore reale per gli oggetti di gioco.",
    "cases.c2.tag1": "Asset Digitali",
    "cases.c2.tag2": "Economia di Gioco",
    "cases.c3.metric": "Carico di lavoro manuale eliminato",
    "cases.c3.industry": "Enterprise",
    "cases.c3.desc": "Una multinazionale ha automatizzato i processi operativi core usando gli smart contract Dyneros Chain, sostituendo le catene di approvazione manuale e la riconciliazione.",
    "cases.c3.tag1": "Automazione Processi",
    "cases.c3.tag2": "Enterprise",
    // PRICING
    "pricing.badge": "Prezzi",
    "pricing.headline": "Piani Semplici e Trasparenti",
    "pricing.sub": "Nessun costo nascosto. Nessun lock-in. Scala quando sei pronto.",
    "pricing.popular": "Più Popolare",
    "pricing.contact": "Contattaci",
    "pricing.for_pricing": "per i prezzi",
    "pricing.custom": "Su misura",
    "pricing.custom_note": "prezzi personalizzati",
    "pricing.p1.name": "Starter",
    "pricing.p1.target": "Piccoli team",
    "pricing.p1.desc": "Tutto il necessario per iniziare su Dyneros Chain.",
    "pricing.p1.f1": "Accesso rete condivisa",
    "pricing.p1.f2": "Fino a 10.000 tx/mese",
    "pricing.p1.f3": "Accesso Explorer e Wallet",
    "pricing.p1.cta": "Inizia Ora",
    "pricing.p2.name": "Business",
    "pricing.p2.target": "Aziende in crescita",
    "pricing.p2.desc": "Risorse dedicate e supporto prioritario per team in espansione.",
    "pricing.p2.f1": "Istanza nodo dedicata",
    "pricing.p2.f2": "Fino a 500.000 tx/mese",
    "pricing.p2.f3": "Deploy di smart contract",
    "pricing.p2.cta": "Contatta le Vendite",
    "pricing.p3.name": "Enterprise",
    "pricing.p3.target": "Grandi Aziende",
    "pricing.p3.desc": "Piena proprietà dell'infrastruttura, strumenti di conformità e garanzie SLA.",
    "pricing.p3.f1": "Deploy chain privata",
    "pricing.p3.f2": "Transazioni illimitate",
    "pricing.p3.f3": "SLA dedicato e conformità",
    "pricing.p3.cta": "Richiedi Demo",
    "pricing.note": "Tutti i piani includono monitoraggio della rete, documentazione tecnica e supporto all'onboarding. I clienti Enterprise ricevono un account manager dedicato.",
    // SUPPORT
    "support.badge": "Supporto",
    "support.headline": "Sempre Disponibili",
    "support.sub": "Il tuo successo è il nostro successo. Supporto tecnico diretto da ingegneri che conoscono la piattaforma.",
    "support.chat.title": "Chat con il Supporto",
    "support.chat.desc": "Parla direttamente con il nostro team tecnico.",
    "support.chat.cta": "Apri Chat",
    "support.status.title": "Status della Rete",
    "support.status.desc": "Monitora in tempo reale la salute dell'infrastruttura Dyneros.",
    "support.status.cta": "Visualizza Status",
    "support.docs.title": "Documentazione",
    "support.docs.desc": "Guide, riferimenti API e tutorial per costruire su Dyneros.",
    "support.docs.cta": "Leggi i Docs",
    // COMPANY
    "company.badge": "Azienda",
    "company.headline1": "Il Layer Infrastrutturale",
    "company.headline2": "per le Imprese di Domani",
    "company.vision": "Dyneros è stata fondata sulla premessa che l'infrastruttura digitale di livello enterprise non dovrebbe richiedere un team di specialisti per essere gestita. Costruiamo i sistemi che alimentano la prossima generazione di aziende — affidabili, scalabili e costruiti per durare.",
    "company.mission": "La nostra missione è rendere l'infrastruttura blockchain accessibile e affidabile come il cloud computing, senza la complessità che ha storicamente limitato l'adozione enterprise.",
    "company.m1.label": "Ingegneri Core",
    "company.m1.detail": "100+ collaboratori globali",
    "company.m2.label": "Portata dell'Infrastruttura",
    "company.m2.detail": "Deployment multi-regione",
    "company.m3.label": "Fase di Crescita",
    "company.m3.detail": "Espansione adozione enterprise",
    "company.cta.headline": "Pronto a costruire su Dyneros?",
    "company.cta.sub": "Parla con il nostro team dei tuoi requisiti infrastrutturali.",
    "company.cta.contact": "Contattaci",
    "company.cta.demo": "Scopri di Più",
    // FOOTER
    "footer.tagline": "Infrastruttura digitale per la prossima generazione di imprese.",
    "footer.col.product": "Prodotto",
    "footer.col.solutions": "Soluzioni",
    "footer.col.network": "Rete",
    "footer.col.company": "Azienda",
    "footer.link.chain": "Dyneros Chain",
    "footer.link.platform": "Piattaforma",
    "footer.link.developers": "Sviluppatori",
    "footer.link.pricing": "Prezzi",
    "footer.link.manufacturing": "Manifattura",
    "footer.link.logistics": "Logistica",
    "footer.link.finance": "Finanza",
    "footer.link.gaming": "Gaming",
    "footer.link.about": "Chi Siamo",
    "footer.link.services": "Servizi",
    "footer.link.support": "Supporto",
    "footer.link.contact": "Contatti",
    "footer.legal.terms": "Termini e Condizioni",
    "footer.legal.disclaimer": "Disclaimer Legale",
    "footer.legal.section": "Legale",
    "footer.legal.manage_cookies": "Gestisci Cookie",
    "footer.legal.reset_cookies": "Reimposta Cookie",
    "footer.systems_ok": "Tutti i sistemi operativi",
    "footer.disclaimer": "Dyneros è una piattaforma tecnologica. Il token DYN è un utility token. Non viene prestata consulenza finanziaria.",
    "footer.copyright": "Dyneros Ltd. Tutti i diritti riservati.",
    // COOKIE BANNER
    "cookie.title": "Utilizziamo i Cookie",
    "cookie.desc": "Utilizziamo cookie tecnici necessari per il funzionamento del sito e, con il tuo consenso, cookie analitici per migliorare la tua esperienza. Non utilizziamo cookie pubblicitari o di profilazione.",
    "cookie.accept": "Accetta Tutti",
    "cookie.reject": "Rifiuta Tutti",
    "cookie.customize": "Personalizza",
    "cookie.save": "Salva Preferenze",
    "cookie.analytics": "Cookie Analitici",
    "cookie.analytics.desc": "Ci aiutano a capire come usi il sito per migliorarlo.",
    // AUTH
    "auth.login.title": "Bentornato",
    "auth.login.sub": "Accedi al tuo pannello di controllo Dyneros.",
    "auth.login.email": "Email",
    "auth.login.password": "Password",
    "auth.login.forgot": "Password dimenticata?",
    "auth.login.cta": "Accedi",
    "auth.login.no_account": "Non hai un account?",
    "auth.login.register": "Registrati",
    "auth.register.title": "Crea il tuo account",
    "auth.register.sub": "Inizia con Dyneros oggi.",
    "auth.register.name": "Nome completo",
    "auth.register.company": "Azienda",
    "auth.register.email": "Email",
    "auth.register.password": "Password",
    "auth.register.confirm": "Conferma password",
    "auth.register.cta": "Crea Account",
    "auth.register.have_account": "Hai già un account?",
    "auth.register.login": "Accedi",
    "auth.forgot.title": "Password dimenticata?",
    "auth.forgot.sub": "Inserisci la tua email e ti invieremo un link per reimpostare la password.",
    "auth.forgot.cta": "Invia link di reset",
    "auth.forgot.back": "Torna al login",
    "auth.forgot.sent.title": "Email inviata!",
    "auth.forgot.sent.sub1": "Se l'indirizzo",
    "auth.forgot.sent.sub2": "è registrato, riceverai un link per reimpostare la password entro pochi minuti.",
    "auth.reset.title": "Nuova password",
    "auth.reset.sub": "Scegli una nuova password sicura per il tuo account.",
    "auth.reset.new": "Nuova password",
    "auth.reset.confirm": "Conferma password",
    "auth.reset.cta": "Reimposta password",
    "auth.reset.done.title": "Password aggiornata!",
    "auth.reset.done.sub": "La tua password è stata reimpostata con successo.",
    "auth.reset.done.cta": "Vai al login",
    "auth.verify.title": "Verifica Email",
    "auth.verify.success": "Email verificata con successo!",
    "auth.verify.redirect": "Verrai reindirizzato al login tra pochi secondi...",
    "auth.verify.invalid": "Link di verifica non valido o scaduto.",
    "auth.verify.cta": "Vai al login",
    // DASHBOARD LAYOUT
    "dash.customer_id": "ID Cliente",
    "dash.group.main": "Principale",
    "dash.group.commercial": "Commerciale",
    "dash.group.blockchain": "Blockchain",
    "dash.group.digital": "Servizi Digitali",
    "dash.group.account": "Account",
    "dash.nav.tickets": "Ticket & Supporto",
    "dash.nav.contracts": "Preventivi & Contratti",
    "dash.nav.invoices": "Fatture & Pagamenti",
    "dash.nav.blockchain": "Blockchain / Web3",
    "dash.nav.wallet": "Wallet & Assets",
    "dash.nav.domains": "Domini / Hosting",
    "dash.nav.ai": "AI & Automazioni",
    "dash.nav.team": "Team / Referenti",
    "dash.nav.apikeys": "API / Accessi",
    "dash.nav.email": "Email & Notifiche",
    "dash.overview": "Panoramica",
    "dash.projects": "Progetti",
    "dash.tickets": "Ticket",
    "dash.documents": "Documenti",
    "dash.contracts": "Contratti",
    "dash.invoices": "Fatture",
    "dash.blockchain": "Blockchain Console",
    "dash.wallet": "Wallet & Asset",
    "dash.smartcontracts": "Smart Contracts",
    "dash.domains": "Domini & Deploy",
    "dash.ai": "AI & Automazioni",
    "dash.team": "Team & Referenti",
    "dash.notifications": "Notifiche",
    "dash.settings": "Impostazioni",
    "dash.security": "Sicurezza",
    "dash.apikeys": "Chiavi API",
    "dash.knowledge": "Knowledge Base",
    "dash.email": "Email & Notifiche",
    "dash.search": "Cerca...",
    "dash.logout": "Esci",
    // DASHBOARD HOME
    "home.welcome": "Benvenuto",
    "home.customer_id": "Customer ID",
    "home.plan": "Piano",
    "home.status": "Stato",
    "home.account_manager": "Account Manager",
    "home.kpi.projects": "Progetti Attivi",
    "home.kpi.tickets": "Ticket Aperti",
    "home.kpi.invoices": "Fatture in Sospeso",
    "home.kpi.contracts": "Contratti Attivi",
    "home.kpi.documents": "Documenti",
    "home.kpi.wallets": "Wallet",
    "home.kpi.domains": "Domini",
    "home.kpi.ai": "Progetti AI",
    "home.kpi.notifications": "Notifiche",
    "home.activity": "Attività Recente",
    "home.priority": "Priorità Alta",
    // COMMON ACTIONS
    "action.search": "Cerca...",
    "action.filter": "Filtra",
    "action.create": "Crea Nuovo",
    "action.save": "Salva",
    "action.cancel": "Annulla",
    "action.delete": "Elimina",
    "action.edit": "Modifica",
    "action.view": "Visualizza",
    "action.download": "Scarica",
    "action.copy": "Copia",
    "action.copied": "Copiato!",
    "action.markread": "Segna come letto",
    "action.markallread": "Segna tutti come letti",
    "action.generate": "Genera",
    "action.revoke": "Revoca",
    "action.send": "Invia",
    "action.test": "Test",
    "action.back": "Indietro",
    "action.close": "Chiudi",
    "action.confirm": "Conferma",
    "action.reply": "Rispondi",
    "action.upload": "Carica",
    "action.refresh": "Aggiorna",
    // STATUSES
    "status.active": "Attivo",
    "status.inactive": "Inattivo",
    "status.pending": "In Attesa",
    "status.completed": "Completato",
    "status.in_progress": "In Corso",
    "status.on_hold": "In Pausa",
    "status.planning": "Pianificazione",
    "status.open": "Aperto",
    "status.resolved": "Risolto",
    "status.closed": "Chiuso",
    "status.paid": "Pagata",
    "status.unpaid": "Non Pagata",
    "status.overdue": "Scaduta",
    "status.draft": "Bozza",
    "status.signed": "Firmato",
    "status.expired": "Scaduto",
    "status.verified": "Verificato",
    "status.unverified": "Non Verificato",
    "status.ssl_ok": "SSL OK",
    "status.ssl_expiring": "SSL in Scadenza",
    "status.ssl_expired": "SSL Scaduto",
    "status.deployed": "Deployato",
    "status.building": "In Build",
    "status.failed": "Fallito",
    "status.running": "In Esecuzione",
    "status.stopped": "Fermo",
    "status.training": "In Training",
    // PRIORITIES
    "priority.low": "Bassa",
    "priority.medium": "Media",
    "priority.high": "Alta",
    "priority.critical": "Critica",
    // LABELS
    "label.name": "Nome",
    "label.email": "Email",
    "label.company": "Azienda",
    "label.status": "Stato",
    "label.priority": "Priorità",
    "label.date": "Data",
    "label.amount": "Importo",
    "label.type": "Tipo",
    "label.description": "Descrizione",
    "label.address": "Indirizzo",
    "label.network": "Rete",
    "label.balance": "Saldo",
    "label.verified": "Verificato",
    "label.all": "Tutti",
    "label.loading": "Caricamento...",
    "label.nodata": "Nessun dato disponibile",
    "label.total": "Totale",
    "label.sla": "SLA",
    "label.progress": "Progresso",
    "label.eta": "Data Prevista",
    "label.created": "Creato",
    "label.updated": "Aggiornato",
    "label.expires": "Scade",
    "label.role": "Ruolo",
    "label.permissions": "Permessi",
    "label.lastused": "Ultimo Utilizzo",
    "label.session": "Sessione",
    "label.ip": "Indirizzo IP",
    "label.device": "Dispositivo",
    "label.language": "Lingua",
    "label.theme": "Tema",
    "label.dark": "Scuro",
    "label.light": "Chiaro",
    "label.italian": "Italiano",
    "label.english": "English",
    "label.project": "Progetto",
    "label.ticket": "Ticket",
    "label.invoice": "Fattura",
    "label.contract": "Contratto",
    "label.document": "Documento",
    "label.wallet": "Wallet",
    "label.domain": "Dominio",
    "label.chain": "Chain",
    "label.block": "Blocco",
    "label.hash": "Hash",
    "label.tx": "Transazione",
    "label.abi": "ABI",
    "label.ssl": "SSL",
    "label.dns": "DNS",
    "label.hosting": "Hosting",
    "label.environment": "Ambiente",
    "label.production": "Produzione",
    "label.staging": "Staging",
    "label.model": "Modello",
    "label.accuracy": "Accuratezza",
    "label.requests": "Richieste",
    "label.key": "Chiave",
    "label.secret": "Segreto",
    "label.usage": "Utilizzo",
    "label.limit": "Limite",
    "label.category": "Categoria",
    "label.size": "Dimensione",
    "label.format": "Formato",
    "label.author": "Autore",
    "label.subject": "Oggetto",
    "label.message": "Messaggio",
    "label.reply": "Risposta",
    "label.attachment": "Allegato",
    "label.tags": "Tag",
    "label.notes": "Note",
    "label.value": "Valore",
    "label.currency": "Valuta",
    "label.due_date": "Scadenza",
    "label.issue_date": "Data Emissione",
    "label.start_date": "Data Inizio",
    "label.end_date": "Data Fine",
    "label.duration": "Durata",
    "label.milestone": "Milestone",
    "label.team": "Team",
    "label.contact": "Contatto",
    "label.phone": "Telefono",
    "label.website": "Sito Web",
    "label.location": "Posizione",
    "label.timezone": "Fuso Orario",
    "label.notifications": "Notifiche",
    "label.security": "Sicurezza",
    "label.profile": "Profilo",
    "label.password": "Password",
    "label.current_password": "Password Attuale",
    "label.new_password": "Nuova Password",
    "label.confirm_password": "Conferma Password",
    "label.two_factor": "Autenticazione a Due Fattori",
    "label.audit_log": "Audit Log",
    "label.active_sessions": "Sessioni Attive",
    "label.api_key": "Chiave API",
    "label.read_only": "Sola Lettura",
    "label.read_write": "Lettura/Scrittura",
    "label.admin": "Amministratore",
    "label.user": "Utente",
    "label.owner": "Proprietario",
    "label.member": "Membro",
    "label.viewer": "Visualizzatore",
    // MESSAGES
    "msg.success": "Operazione completata con successo",
    "msg.error": "Si è verificato un errore",
    "msg.saved": "Salvato con successo",
    "msg.deleted": "Eliminato con successo",
    "msg.sent": "Inviato con successo",
    "msg.generated": "Generato con successo",
    "msg.revoked": "Revocato con successo",
    "msg.comingsoon": "Funzionalità in arrivo",
    "msg.copied": "Copiato negli appunti",
    "msg.confirm_delete": "Sei sicuro di voler eliminare questo elemento?",
    "msg.confirm_revoke": "Sei sicuro di voler revocare questo elemento?",
    "msg.no_notifications": "Nessuna notifica",
    "msg.no_projects": "Nessun progetto trovato",
    "msg.no_tickets": "Nessun ticket trovato",
    "msg.no_invoices": "Nessuna fattura trovata",
    "msg.no_contracts": "Nessun contratto trovato",
    "msg.no_documents": "Nessun documento trovato",
    "msg.no_keys": "Nessuna chiave API trovata",
    "msg.loading": "Caricamento in corso...",
    "msg.error_load": "Errore nel caricamento dei dati",
  },
  en: {
    // NAV
    "nav.chain": "Dyneros Chain",
    "nav.platform": "Platform",
    "nav.solutions": "Solutions",
    "nav.developers": "Developers",
    "nav.pricing": "Pricing",
    "nav.company": "Company",
    "nav.login": "Login",
    "nav.register": "Get Started",
    "nav.dashboard": "Dashboard",
    "nav.logout": "Logout",
    // HERO
    "hero.badge": "Dyneros Chain — Live on Mainnet",
    "hero.headline1": "Digital Infrastructure",
    "hero.headline2": "for the Next Generation",
    "hero.headline3": "of Enterprises",
    "hero.sub": "Dyneros builds scalable and secure systems for modern enterprises — on-chain and beyond.",
    "hero.cta.start": "Get Started",
    "hero.cta.explore": "Explore Dyneros Chain",
    "hero.stat1.label": "Network Uptime",
    "hero.stat2.label": "Transactions Processed",
    "hero.stat3.label": "Enterprise Clients",
    // TRUST BAR
    "trust.p1.label": "Enterprise-ready infrastructure",
    "trust.p1.desc": "Designed for compliance, control, and predictability at scale.",
    "trust.p2.label": "Global development network",
    "trust.p2.desc": "15 core engineers and 100+ contributors across every timezone.",
    "trust.p3.label": "Scalable from day one",
    "trust.p3.desc": "Architecture that grows with your company — without re-platforming.",
    // CHAIN SECTION
    "chain.badge": "Dyneros Chain",
    "chain.headline": "The Blockchain Built for Enterprises",
    "chain.sub": "A dedicated, high-performance blockchain layer for companies that need control, predictability, and compliance — without the noise of public networks.",
    "chain.vs.public.title": "Public blockchains",
    "chain.vs.public.desc": "Unpredictable costs, public data, no control over infrastructure.",
    "chain.vs.dyneros.title": "Dyneros Chain",
    "chain.vs.dyneros.desc": "Fixed costs, private data, full ownership of your blockchain environment.",
    "chain.feat1.title": "High Availability",
    "chain.feat1.desc": "99.9% guaranteed uptime with multi-node redundancy and automatic failover.",
    "chain.feat2.title": "EVM Compatible",
    "chain.feat2.desc": "Deploy your existing Solidity smart contracts without modifications.",
    "chain.feat3.title": "Built-in Compliance",
    "chain.feat3.desc": "Audit tools and access controls designed for regulated environments.",
    "chain.feat4.title": "Predictable Costs",
    "chain.feat4.desc": "Fixed per-transaction pricing — no surprises from variable gas fees.",
    "chain.feat5.title": "Private Data",
    "chain.feat5.desc": "Your chain, your data. No public exposure by default.",
    "chain.feat6.title": "Enterprise Support",
    "chain.feat6.desc": "Dedicated SLA, account manager, and direct 24/7 technical support.",
    "chain.network.title": "Network Access",
    "chain.network.sub": "Connect directly to the Dyneros Chain infrastructure.",
    "chain.quote": "Not a cryptocurrency. An infrastructure.",
    "chain.explorer": "Open Explorer",
    "chain.wallet": "Access Wallet",
    // PLATFORM SECTION
    "platform.badge": "Platform",
    "platform.headline": "The Complete Platform Experience",
    "platform.sub": "All the tools your team needs to operate, monitor, and manage your blockchain infrastructure.",
    "platform.explorer.title": "Explorer — explorer.dyneros.com",
    "platform.explorer.label": "Explorer",
    "platform.explorer.desc": "Full visibility into transactions and blocks on the Dyneros Chain.",
    "platform.wallet.title": "Wallet — wallet.dyneros.com",
    "platform.wallet.label": "Wallet",
    "platform.wallet.desc": "Secure asset and account management for enterprise users.",
    "platform.dashboard.title": "Network Dashboard",
    "platform.dashboard.label": "Dashboard",
    "platform.dashboard.desc": "Real-time overview of the chain with performance metrics and health indicators.",
    "platform.search": "Search transactions, blocks, addresses...",
    "platform.balance": "Total Balance",
    "platform.send": "Send",
    "platform.receive": "Receive",
    "platform.history": "History",
    "platform.confirmed": "Confirmed",
    "platform.block": "Block",
    "platform.validators": "Validators",
    "platform.blocks": "Blocks",
    // SOLUTIONS SECTION
    "solutions.badge": "Solutions",
    "solutions.headline": "Built for Your Industry",
    "solutions.sub": "Real problems. Concrete solutions. Measurable results.",
    "solutions.problem": "Problem",
    "solutions.solution": "Solution",
    "solutions.outcome": "Outcome",
    "solutions.ind1.name": "Manufacturing",
    "solutions.ind1.problem": "Traceability gaps across supply chains create disputes and compliance failures.",
    "solutions.ind1.solution": "On-chain supply chain with immutable records at every production stage.",
    "solutions.ind1.outcome": "Complete audit trail, zero disputes, regulatory compliance by default.",
    "solutions.ind2.name": "Logistics",
    "solutions.ind2.problem": "Document fraud and manual certifications slow down cross-border operations.",
    "solutions.ind2.solution": "Digital certification with cryptographic verification of every shipment.",
    "solutions.ind2.outcome": "Immutable shipping records, faster customs clearance, fraud elimination.",
    "solutions.ind3.name": "Finance",
    "solutions.ind3.problem": "Slow settlement cycles and high transaction costs erode margins.",
    "solutions.ind3.solution": "Internal payment channels built on Dyneros Chain for instant settlement.",
    "solutions.ind3.outcome": "Instant, low-cost transfers with full auditability and compliance.",
    "solutions.ind4.name": "Retail",
    "solutions.ind4.problem": "Fragmented loyalty programs fail to retain customers or generate data.",
    "solutions.ind4.solution": "Tokenized loyalty infrastructure — programmable, portable, interoperable.",
    "solutions.ind4.outcome": "Unified rewards, higher retention, and actionable customer intelligence.",
    "solutions.ind5.name": "Gaming",
    "solutions.ind5.problem": "Game economies are exploited, undermining player trust and monetization.",
    "solutions.ind5.solution": "Verifiable digital asset economy with on-chain ownership and provenance.",
    "solutions.ind5.outcome": "Verifiable ownership, real asset value, sustainable game economy.",
    "solutions.ind6.name": "Startups",
    "solutions.ind6.problem": "Infrastructure costs and complexity slow down product development cycles.",
    "solutions.ind6.solution": "Scalable blockchain foundations with managed infrastructure from day one.",
    "solutions.ind6.outcome": "Launch faster, scale at lower cost, focus on product not infrastructure.",
    // SERVICES SECTION
    "services.badge": "Services",
    "services.headline": "What We Build",
    "services.sub": "From custom software to enterprise blockchain infrastructure — we build systems that work at scale, from day one.",
    "services.cta": "Talk to Us",
    "services.s1.title": "Software Development",
    "services.s1.desc": "Production-grade software designed for reliability, performance, and long-term maintainability.",
    "services.s2.title": "Web Platforms",
    "services.s2.desc": "Scalable web applications built for enterprise traffic, complex workflows, and a smooth user experience.",
    "services.s3.title": "Blockchain Solutions",
    "services.s3.desc": "End-to-end blockchain integration — from architecture to deployment on Dyneros Chain or custom networks.",
    "services.s4.title": "Custom Systems",
    "services.s4.desc": "Bespoke infrastructure and tools designed around your operational requirements, not the other way around.",
    // DEVELOPERS SECTION
    "dev.badge": "For Builders",
    "dev.headline": "Build on Dyneros",
    "dev.sub": "Access the Dyneros Chain infrastructure through clean, well-documented interfaces. No internal complexity exposed — just the tools you need to build.",
    "dev.cta": "Start Building",
    "dev.ap1.title": "Network Access",
    "dev.ap1.desc": "Connect your applications directly to the Dyneros Chain mainnet or a dedicated private instance.",
    "dev.ap2.title": "Smart Contract Deploy",
    "dev.ap2.desc": "Deploy and manage smart contracts on Dyneros Chain using the development tools you already know.",
    "dev.ap3.title": "API Integration",
    "dev.ap3.desc": "RESTful and GraphQL APIs to read chain state, submit transactions, and monitor events.",
    "dev.deployed": "Deployed at:",
    // CASE STUDIES
    "cases.badge": "Proof",
    "cases.headline": "Results That Speak",
    "cases.sub": "Real deployments. Measurable impact. No empty marketing.",
    "cases.c1.metric": "Reduction in operational costs",
    "cases.c1.industry": "Logistics",
    "cases.c1.desc": "A global logistics operator migrated document certification to Dyneros Chain, eliminating manual verification workflows and cross-border disputes.",
    "cases.c1.tag1": "Document Management",
    "cases.c1.tag2": "Supply Chain",
    "cases.c2.metric": "Digital asset transactions in Q1",
    "cases.c2.industry": "Gaming",
    "cases.c2.desc": "A major gaming platform deployed a digital asset economy on Dyneros Chain, enabling verifiable ownership and real-value trading for in-game items.",
    "cases.c2.tag1": "Digital Assets",
    "cases.c2.tag2": "Game Economy",
    "cases.c3.metric": "Manual workload eliminated",
    "cases.c3.industry": "Enterprise",
    "cases.c3.desc": "A multinational automated core operational processes using Dyneros Chain smart contracts, replacing manual approval chains and reconciliation.",
    "cases.c3.tag1": "Process Automation",
    "cases.c3.tag2": "Enterprise",
    // PRICING
    "pricing.badge": "Pricing",
    "pricing.headline": "Simple and Transparent Plans",
    "pricing.sub": "No hidden costs. No lock-in. Scale when you're ready.",
    "pricing.popular": "Most Popular",
    "pricing.contact": "Contact us",
    "pricing.for_pricing": "for pricing",
    "pricing.custom": "Custom",
    "pricing.custom_note": "custom pricing",
    "pricing.p1.name": "Starter",
    "pricing.p1.target": "Small teams",
    "pricing.p1.desc": "Everything you need to get started on Dyneros Chain.",
    "pricing.p1.f1": "Shared network access",
    "pricing.p1.f2": "Up to 10,000 tx/month",
    "pricing.p1.f3": "Explorer and Wallet access",
    "pricing.p1.cta": "Get Started",
    "pricing.p2.name": "Business",
    "pricing.p2.target": "Growing companies",
    "pricing.p2.desc": "Dedicated resources and priority support for expanding teams.",
    "pricing.p2.f1": "Dedicated node instance",
    "pricing.p2.f2": "Up to 500,000 tx/month",
    "pricing.p2.f3": "Smart contract deploy",
    "pricing.p2.cta": "Contact Sales",
    "pricing.p3.name": "Enterprise",
    "pricing.p3.target": "Large Enterprises",
    "pricing.p3.desc": "Full infrastructure ownership, compliance tools, and SLA guarantees.",
    "pricing.p3.f1": "Private chain deploy",
    "pricing.p3.f2": "Unlimited transactions",
    "pricing.p3.f3": "Dedicated SLA & compliance",
    "pricing.p3.cta": "Request Demo",
    "pricing.note": "All plans include network monitoring, technical documentation, and onboarding support. Enterprise customers receive a dedicated account manager.",
    // SUPPORT
    "support.badge": "Support",
    "support.headline": "Always Available",
    "support.sub": "Your success is our success. Direct technical support from engineers who know the platform.",
    "support.chat.title": "Chat with Support",
    "support.chat.desc": "Talk directly with our technical team.",
    "support.chat.cta": "Open Chat",
    "support.status.title": "Network Status",
    "support.status.desc": "Monitor the health of the Dyneros infrastructure in real time.",
    "support.status.cta": "View Status",
    "support.docs.title": "Documentation",
    "support.docs.desc": "Guides, API references, and tutorials for building on Dyneros.",
    "support.docs.cta": "Read Docs",
    // COMPANY
    "company.badge": "Company",
    "company.headline1": "The Infrastructure Layer",
    "company.headline2": "for Tomorrow's Enterprises",
    "company.vision": "Dyneros was founded on the premise that enterprise-grade digital infrastructure should not require a team of specialists to manage. We build the systems that power the next generation of companies — reliable, scalable, and built to last.",
    "company.mission": "Our mission is to make blockchain infrastructure as accessible and reliable as cloud computing, without the complexity that has historically limited enterprise adoption.",
    "company.m1.label": "Core Engineers",
    "company.m1.detail": "100+ global contributors",
    "company.m2.label": "Infrastructure Reach",
    "company.m2.detail": "Multi-region deployment",
    "company.m3.label": "Growth Stage",
    "company.m3.detail": "Enterprise adoption expansion",
    "company.cta.headline": "Ready to build on Dyneros?",
    "company.cta.sub": "Talk with our team about your infrastructure requirements.",
    "company.cta.contact": "Contact Us",
    "company.cta.demo": "Learn More",
    // FOOTER
    "footer.tagline": "Digital infrastructure for the next generation of enterprises.",
    "footer.col.product": "Product",
    "footer.col.solutions": "Solutions",
    "footer.col.network": "Network",
    "footer.col.company": "Company",
    "footer.link.chain": "Dyneros Chain",
    "footer.link.platform": "Platform",
    "footer.link.developers": "Developers",
    "footer.link.pricing": "Pricing",
    "footer.link.manufacturing": "Manufacturing",
    "footer.link.logistics": "Logistics",
    "footer.link.finance": "Finance",
    "footer.link.gaming": "Gaming",
    "footer.link.about": "About Us",
    "footer.link.services": "Services",
    "footer.link.support": "Support",
    "footer.link.contact": "Contact",
    "footer.legal.terms": "Terms & Conditions",
    "footer.legal.disclaimer": "Legal Disclaimer",
    "footer.legal.section": "Legal",
    "footer.legal.manage_cookies": "Manage Cookies",
    "footer.legal.reset_cookies": "Reset Cookies",
    "footer.systems_ok": "All systems operational",
    "footer.disclaimer": "Dyneros is a technology platform. The DYN token is a utility token. No financial advice is provided.",
    "footer.copyright": "Dyneros Ltd. All rights reserved.",
    // COOKIE BANNER
    "cookie.title": "We Use Cookies",
    "cookie.desc": "We use technically necessary cookies for the website to function and, with your consent, analytical cookies to improve your experience. We do not use advertising or profiling cookies.",
    "cookie.accept": "Accept All",
    "cookie.reject": "Reject All",
    "cookie.customize": "Customize",
    "cookie.save": "Save Preferences",
    "cookie.analytics": "Analytical Cookies",
    "cookie.analytics.desc": "Help us understand how you use the site to improve it.",
    // AUTH
    "auth.login.title": "Welcome back",
    "auth.login.sub": "Sign in to your Dyneros control panel.",
    "auth.login.email": "Email",
    "auth.login.password": "Password",
    "auth.login.forgot": "Forgot password?",
    "auth.login.cta": "Sign In",
    "auth.login.no_account": "Don't have an account?",
    "auth.login.register": "Sign up",
    "auth.register.title": "Create your account",
    "auth.register.sub": "Get started with Dyneros today.",
    "auth.register.name": "Full name",
    "auth.register.company": "Company",
    "auth.register.email": "Email",
    "auth.register.password": "Password",
    "auth.register.confirm": "Confirm password",
    "auth.register.cta": "Create Account",
    "auth.register.have_account": "Already have an account?",
    "auth.register.login": "Sign in",
    "auth.forgot.title": "Forgot password?",
    "auth.forgot.sub": "Enter your email and we will send you a link to reset your password.",
    "auth.forgot.cta": "Send reset link",
    "auth.forgot.back": "Back to login",
    "auth.forgot.sent.title": "Email sent!",
    "auth.forgot.sent.sub1": "If the address",
    "auth.forgot.sent.sub2": "is registered, you will receive a reset link within a few minutes.",
    "auth.reset.title": "New password",
    "auth.reset.sub": "Choose a new secure password for your account.",
    "auth.reset.new": "New password",
    "auth.reset.confirm": "Confirm password",
    "auth.reset.cta": "Reset password",
    "auth.reset.done.title": "Password updated!",
    "auth.reset.done.sub": "Your password has been reset successfully.",
    "auth.reset.done.cta": "Go to login",
    "auth.verify.title": "Email Verification",
    "auth.verify.success": "Email verified successfully!",
    "auth.verify.redirect": "You will be redirected to login in a few seconds...",
    "auth.verify.invalid": "Invalid or expired verification link.",
    "auth.verify.cta": "Go to login",
    // DASHBOARD LAYOUT
    "dash.customer_id": "Customer ID",
    "dash.group.main": "Main",
    "dash.group.commercial": "Commercial",
    "dash.group.blockchain": "Blockchain",
    "dash.group.digital": "Digital Services",
    "dash.group.account": "Account",
    "dash.nav.tickets": "Tickets & Support",
    "dash.nav.contracts": "Quotes & Contracts",
    "dash.nav.invoices": "Invoices & Payments",
    "dash.nav.blockchain": "Blockchain / Web3",
    "dash.nav.wallet": "Wallet & Assets",
    "dash.nav.domains": "Domains / Hosting",
    "dash.nav.ai": "AI & Automations",
    "dash.nav.team": "Team / Contacts",
    "dash.nav.apikeys": "API / Access",
    "dash.nav.email": "Email & Notifications",
    "dash.overview": "Overview",
    "dash.projects": "Projects",
    "dash.tickets": "Tickets",
    "dash.documents": "Documents",
    "dash.contracts": "Contracts",
    "dash.invoices": "Invoices",
    "dash.blockchain": "Blockchain Console",
    "dash.wallet": "Wallet & Assets",
    "dash.smartcontracts": "Smart Contracts",
    "dash.domains": "Domains & Deploy",
    "dash.ai": "AI & Automations",
    "dash.team": "Team & Contacts",
    "dash.notifications": "Notifications",
    "dash.settings": "Settings",
    "dash.security": "Security",
    "dash.apikeys": "API Keys",
    "dash.knowledge": "Knowledge Base",
    "dash.email": "Email & Notifications",
    "dash.search": "Search...",
    "dash.logout": "Logout",
    // DASHBOARD HOME
    "home.welcome": "Welcome",
    "home.customer_id": "Customer ID",
    "home.plan": "Plan",
    "home.status": "Status",
    "home.account_manager": "Account Manager",
    "home.kpi.projects": "Active Projects",
    "home.kpi.tickets": "Open Tickets",
    "home.kpi.invoices": "Pending Invoices",
    "home.kpi.contracts": "Active Contracts",
    "home.kpi.documents": "Documents",
    "home.kpi.wallets": "Wallets",
    "home.kpi.domains": "Domains",
    "home.kpi.ai": "AI Projects",
    "home.kpi.notifications": "Notifications",
    "home.activity": "Recent Activity",
    "home.priority": "High Priority",
    // COMMON ACTIONS
    "action.search": "Search...",
    "action.filter": "Filter",
    "action.create": "Create New",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.view": "View",
    "action.download": "Download",
    "action.copy": "Copy",
    "action.copied": "Copied!",
    "action.markread": "Mark as read",
    "action.markallread": "Mark all as read",
    "action.generate": "Generate",
    "action.revoke": "Revoke",
    "action.send": "Send",
    "action.test": "Test",
    "action.back": "Back",
    "action.close": "Close",
    "action.confirm": "Confirm",
    "action.reply": "Reply",
    "action.upload": "Upload",
    "action.refresh": "Refresh",
    // STATUSES
    "status.active": "Active",
    "status.inactive": "Inactive",
    "status.pending": "Pending",
    "status.completed": "Completed",
    "status.in_progress": "In Progress",
    "status.on_hold": "On Hold",
    "status.planning": "Planning",
    "status.open": "Open",
    "status.resolved": "Resolved",
    "status.closed": "Closed",
    "status.paid": "Paid",
    "status.unpaid": "Unpaid",
    "status.overdue": "Overdue",
    "status.draft": "Draft",
    "status.signed": "Signed",
    "status.expired": "Expired",
    "status.verified": "Verified",
    "status.unverified": "Unverified",
    "status.ssl_ok": "SSL OK",
    "status.ssl_expiring": "SSL Expiring",
    "status.ssl_expired": "SSL Expired",
    "status.deployed": "Deployed",
    "status.building": "Building",
    "status.failed": "Failed",
    "status.running": "Running",
    "status.stopped": "Stopped",
    "status.training": "Training",
    // PRIORITIES
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.critical": "Critical",
    // LABELS
    "label.name": "Name",
    "label.email": "Email",
    "label.company": "Company",
    "label.status": "Status",
    "label.priority": "Priority",
    "label.date": "Date",
    "label.amount": "Amount",
    "label.type": "Type",
    "label.description": "Description",
    "label.address": "Address",
    "label.network": "Network",
    "label.balance": "Balance",
    "label.verified": "Verified",
    "label.all": "All",
    "label.loading": "Loading...",
    "label.nodata": "No data available",
    "label.total": "Total",
    "label.sla": "SLA",
    "label.progress": "Progress",
    "label.eta": "ETA",
    "label.created": "Created",
    "label.updated": "Updated",
    "label.expires": "Expires",
    "label.role": "Role",
    "label.permissions": "Permissions",
    "label.lastused": "Last Used",
    "label.session": "Session",
    "label.ip": "IP Address",
    "label.device": "Device",
    "label.language": "Language",
    "label.theme": "Theme",
    "label.dark": "Dark",
    "label.light": "Light",
    "label.italian": "Italiano",
    "label.english": "English",
    "label.project": "Project",
    "label.ticket": "Ticket",
    "label.invoice": "Invoice",
    "label.contract": "Contract",
    "label.document": "Document",
    "label.wallet": "Wallet",
    "label.domain": "Domain",
    "label.chain": "Chain",
    "label.block": "Block",
    "label.hash": "Hash",
    "label.tx": "Transaction",
    "label.abi": "ABI",
    "label.ssl": "SSL",
    "label.dns": "DNS",
    "label.hosting": "Hosting",
    "label.environment": "Environment",
    "label.production": "Production",
    "label.staging": "Staging",
    "label.model": "Model",
    "label.accuracy": "Accuracy",
    "label.requests": "Requests",
    "label.key": "Key",
    "label.secret": "Secret",
    "label.usage": "Usage",
    "label.limit": "Limit",
    "label.category": "Category",
    "label.size": "Size",
    "label.format": "Format",
    "label.author": "Author",
    "label.subject": "Subject",
    "label.message": "Message",
    "label.reply": "Reply",
    "label.attachment": "Attachment",
    "label.tags": "Tags",
    "label.notes": "Notes",
    "label.value": "Value",
    "label.currency": "Currency",
    "label.due_date": "Due Date",
    "label.issue_date": "Issue Date",
    "label.start_date": "Start Date",
    "label.end_date": "End Date",
    "label.duration": "Duration",
    "label.milestone": "Milestone",
    "label.team": "Team",
    "label.contact": "Contact",
    "label.phone": "Phone",
    "label.website": "Website",
    "label.location": "Location",
    "label.timezone": "Timezone",
    "label.notifications": "Notifications",
    "label.security": "Security",
    "label.profile": "Profile",
    "label.password": "Password",
    "label.current_password": "Current Password",
    "label.new_password": "New Password",
    "label.confirm_password": "Confirm Password",
    "label.two_factor": "Two-Factor Authentication",
    "label.audit_log": "Audit Log",
    "label.active_sessions": "Active Sessions",
    "label.api_key": "API Key",
    "label.read_only": "Read Only",
    "label.read_write": "Read/Write",
    "label.admin": "Administrator",
    "label.user": "User",
    "label.owner": "Owner",
    "label.member": "Member",
    "label.viewer": "Viewer",
    // MESSAGES
    "msg.success": "Operation completed successfully",
    "msg.error": "An error occurred",
    "msg.saved": "Saved successfully",
    "msg.deleted": "Deleted successfully",
    "msg.sent": "Sent successfully",
    "msg.generated": "Generated successfully",
    "msg.revoked": "Revoked successfully",
    "msg.comingsoon": "Feature coming soon",
    "msg.copied": "Copied to clipboard",
    "msg.confirm_delete": "Are you sure you want to delete this item?",
    "msg.confirm_revoke": "Are you sure you want to revoke this item?",
    "msg.no_notifications": "No notifications",
    "msg.no_projects": "No projects found",
    "msg.no_tickets": "No tickets found",
    "msg.no_invoices": "No invoices found",
    "msg.no_contracts": "No contracts found",
    "msg.no_documents": "No documents found",
    "msg.no_keys": "No API keys found",
    "msg.loading": "Loading...",
    "msg.error_load": "Error loading data",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "it",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("dyneros_lang");
    return (stored === "en" || stored === "it") ? stored : "it";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("dyneros_lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations["it"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
